name: Test

on: [push, pull_request]

jobs:
  gpu:
    runs-on: Linux
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install dependencies
      run: |
        python -m pip install ".[dev]" --upgrade
    - name: test
      run: |
        python -c '15+15'