name: actions_cmd
on:
  issue_comment:
    types: [created]
jobs:
  comment-action:
    runs-on: ubuntu-latest
    steps:
      - env:
        TITLE: ${{github.event.issue.title}}
        DESCRIPTION: ${{github.event.issue.body}}

        run: |
        echo "ISSUE TITLE: $TITLE"
        echo "ISSUE DESCRIPTION: $DESCRIPTION"