name: actions_cmd
on:
  issue_comment:
    types: [created]
jobs:

  comment-action:
    runs-on: ubuntu-latest
    env:
      TITLE: ${{github.event.issue.title}}
      DESCRIPTION: ${{github.event.issue.body}}
    steps:
      - name: "bla"
        run: |
          echo "ISSUE TITLE: $TITLE"
          echo "ISSUE DESCRIPTION: $DESCRIPTION"