name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
      version:
        description: 'Version to deploy'
        required: true
        default: '1.0.0'

jobs:
  deploy:
    runs-on: self-hosted  # Specify that the runner is self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script
        run: |
          echo "Deploying to environment:"
          ${{ github.event.inputs.environment }}
          echo "Deploying version: ${{ github.event.inputs.version }}"
          # Add your custom commands here, e.g.
          # ./deploy.sh ${{ github.event.inputs.environment }} ${{ github.event.inputs.version }}
